INSERT INTO AUTHORITIES (GRANTS, NAME) VALUES ('ADMIN', 'ADMIN AUTH');
INSERT INTO AUTHORITIES (GRANTS, NAME) VALUES ('USER', 'USER AUTH');

INSERT INTO SBGROUP(GROUPNAME, GROUPDESCRIPTION, AUTHORITIES) VALUES ('ADMIN GROUP', 'ADMIN GROUP DESCRIPTION', 1);
INSERT INTO SBGROUP(GROUPNAME, GROUPDESCRIPTION, AUTHORITIES) VALUES ('USER GROUP', 'USER GROUP DESCRIPTION', 2);